### PR TITLE
Add kokkos stuff

### PR DESCRIPTION
**Pull request by HaiwangYu**
@brettviren as we discussed yesterday, I added some kokkos stuff by copying the cuda.py. Kokkos-cuda needs specific cuda options. So I added those options in the kokkos.py.

**This is not fully working right now. Just think this maybe easier to communicate.**

I added `kokkos-options` to manually config how `.kokkos` files should be compiled. I just tested kokkos-cuda. I am working on testing kokko-omp.

This works OK for `.kokkos` sources code in the `src` fold. It gives me error msg if I try to put some `.kokkos` files in the `test` folder. Any ideas how to fix this?
```
Build failed
Traceback (most recent call last):
  File "/home/yuhw/wc/wct-analysis/csi-kokkos/wire-cell-gen-kokkos/.waf3-2.0.20-88888387641ed0f5c08dd6187360302f/waflib/Tools/c_preproc.py", line 663, in scan
    incn=task.generator.includes_nodes
AttributeError: 'task_gen' object has no attribute 'includes_nodes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yuhw/wc/wct-analysis/csi-kokkos/wire-cell-gen-kokkos/.waf3-2.0.20-88888387641ed0f5c08dd6187360302f/waflib/Runner.py", line 255, in task_status
    return tsk.runnable_status()
  File "/home/yuhw/wc/wct-analysis/csi-kokkos/wire-cell-gen-kokkos/.waf3-2.0.20-88888387641ed0f5c08dd6187360302f/waflib/Task.py", line 372, in runnable_status
    new_sig=self.signature()
  File "/home/yuhw/wc/wct-analysis/csi-kokkos/wire-cell-gen-kokkos/.waf3-2.0.20-88888387641ed0f5c08dd6187360302f/waflib/Task.py", line 357, in signature
    self.sig_implicit_deps()
  File "/home/yuhw/wc/wct-analysis/csi-kokkos/wire-cell-gen-kokkos/.waf3-2.0.20-88888387641ed0f5c08dd6187360302f/waflib/Task.py", line 456, in sig_implicit_deps
    (bld.node_deps[key],bld.raw_deps[key])=self.scan()
  File "/home/yuhw/wc/wct-analysis/csi-kokkos/wire-cell-gen-kokkos/.waf3-2.0.20-88888387641ed0f5c08dd6187360302f/waflib/Tools/c_preproc.py", line 665, in scan
    raise Errors.WafError('%r is missing a feature such as "c", "cxx" or "includes": '%task.generator)
waflib.Errors.WafError: bld(source=[/home/yuhw/wc/wct-analysis/csi-kokkos/wire-cell-gen-kokkos/test/test_atadd.kokkos], target='test_atadd', meths=['make_test', 'process_rule', 'process_source'], features=['test'], path=/home/yuhw/wc/wct-analysis/csi-kokkos/wire-cell-gen-kokkos, idx=3, tg_idx_count=3, ut_cwd=/home/yuhw/wc/wct-analysis/csi-kokkos/wire-cell-gen-kokkos, install_path=None, includes=['inc', 'test', 'tests'], use=['BOOST', 'CUDA', 'EIGEN', 'FFTW', 'JSONCPP', 'KOKKOS', 'WCT', 'WireCellGen', 'WireCellIface', 'WireCellUtil', 'WireCellGenKokkos'], typ='program', _name='test_atadd', posted=True) in /home/yuhw/wc/wct-analysis/csi-kokkos/wire-cell-gen-kokkos is missing a feature such as "c", "cxx" or "includes":
```

### CODE REVIEW

**Comment by brettviren** [comment]
It looks like `includes_nodes` get set when at least one of several Waf "features" are turned on.  The operative one here is "cxx" which we have somehow lost from the cuda -> kokkos translation.

You may be able to simply add:

```python

class kokkos_cuda(Task.Task):
    ...
    features = "cxx"
```

**Comment by HaiwangYu** [comment]
Thanks @brettviren , this seems to be working. But there are some more things need to be fixed.

**Review by brettviren — APPROVED** [review]
It looks okay to me.  I don't see any problems with backward compatibility.

**Comment by HaiwangYu** [comment]
Thanks @brettviren , I did use it to build wire-cell-toolkit and it looks OK.

**Pull request merged**
